apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end

spec:
  template:
      metadata:
        name: myapp-pod
        labels:
          app: myapp
          type: front-end
      spec:
        containers:   #A list/array
          - name: nginx-container
            image: nginx:1.17.0
  replicas: 3
  selector:    #This section determines the difference betweena an RC and ReplicaSet
    matchLabels:
      type: front-end
