apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
      metadata:
        name: myapp-pod
        labels:
          name: myapp-pod
          app: myapp
          type: pod
      spec:
        containers:   #A list/array
          - name: nginx-container
            image: nginx
  replicas: 3
